# Generated by Django 5.2 on 2025-05-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contas',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
