# Generated by Django 5.2 on 2025-07-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('consulta_sql', models.TextField()),
                ('formato_exibicao', models.CharField(default='numero', max_length=50)),
                ('icone', models.CharField(default='bi-graph-up', max_length=50)),
                ('cor', models.CharField(default='#3498db', max_length=7)),
                ('ativa', models.BooleanField(default=True)),
                ('ordem_exibicao', models.PositiveIntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estatisticas_metricas_personalizadas',
                'ordering': ['ordem_exibicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AlertaEstatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Informativo'), ('warning', 'Aviso'), ('danger', 'Perigo'), ('success', 'Sucesso')], default='info', max_length=10)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=10)),
                ('metrica_relacionada', models.CharField(blank=True, max_length=100)),
                ('valor_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_esperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acao_sugerida', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estatisticas_alertas',
                'ordering': ['-data_criacao', '-prioridade'],
                'indexes': [models.Index(fields=['tipo', 'ativo'], name='estatistica_tipo_fba12c_idx'), models.Index(fields=['prioridade', 'visualizado'], name='estatistica_priorid_8d75a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='EstatisticaCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dashboard', 'Dashboard Principal'), ('atletas', 'Estatísticas de Atletas'), ('competicoes', 'Estatísticas de Competições'), ('academias', 'Estatísticas de Academias'), ('comparativas', 'Análises Comparativas')], max_length=20)),
                ('chave', models.CharField(max_length=100)),
                ('dados', models.JSONField()),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'estatisticas_cache',
                'indexes': [models.Index(fields=['tipo', 'chave'], name='estatistica_tipo_2e0740_idx'), models.Index(fields=['expira_em'], name='estatistica_expira__0101eb_idx')],
                'unique_together': {('tipo', 'chave')},
            },
        ),
    ]
