# Generated by Django 5.2 on 2025-07-21 23:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competicoes', '0013_chaveamentokumite_partidakumite_pontuacaokumite'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoOnline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_inscricao', models.CharField(blank=True, max_length=20, unique=True)),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('faixa', models.CharField(choices=[('branca', 'Branca'), ('azul', 'Azul'), ('amarela', 'Amarela'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], max_length=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.IntegerField()),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('academia_nome', models.CharField(max_length=100)),
                ('academia_cidade', models.CharField(max_length=50)),
                ('academia_estado', models.CharField(max_length=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='inscricoes_online/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente de Pagamento'), ('pago', 'Pagamento Confirmado'), ('confirmado', 'Inscrição Confirmada'), ('cancelado', 'Cancelado')], default='pendente', max_length=15)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'PIX'), ('cartao', 'Cartão de Crédito'), ('boleto', 'Boleto Bancário')], max_length=10)),
                ('valor_inscricao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('senha_atleta', models.CharField(blank=True, max_length=20)),
                ('senha_enviada', models.BooleanField(default=False)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ip_inscricao', models.GenericIPAddressField(blank=True, null=True)),
                ('academia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competicoes.academia')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.categoria')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_online', to='competicoes.competicao')),
            ],
            options={
                'verbose_name': 'Inscrição Online',
                'verbose_name_plural': 'Inscrições Online',
                'ordering': ['-data_inscricao'],
                'unique_together': {('competicao', 'email')},
            },
        ),
        migrations.CreateModel(
            name='LogInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='inscricoes_online.inscricaoonline')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
