# Generated by Django 5.2 on 2025-05-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competicoes', '0006_alter_competicao_inscricoes_abertas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('idade', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('altura', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('faixa', models.CharField(choices=[('branca', 'Branca'), ('azul', 'Azul'), ('amarela', 'Amarela'), ('laranja', 'Laranja'), ('verde', 'Verde'), ('roxa', 'Roxa'), ('marrom', 'Marrom'), ('preta', 'Preta')], max_length=10)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='atletas/fotos/')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('academia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competicoes.academia')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competicoes.categoria')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to='competicoes.competicao')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'ordering': ['nome_completo'],
            },
        ),
    ]
