# Generated by Django 5.2 on 2025-05-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='foto',
        ),
        migrations.AddField(
            model_name='atleta',
            name='foto_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
