# Generated by Django 5.2 on 2025-05-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0002_remove_atleta_foto_atleta_foto_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('X', 'Misto')], max_length=1),
        ),
    ]
