# Generated by Django 5.2 on 2025-05-28 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0003_alter_atleta_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='altura',
            field=models.IntegerField(default=0),
        )
    ]
