# Generated by Django 5.2 on 2025-05-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0006_alter_atleta_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='altura',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='atleta',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
