# Generated by Django 5.2 on 2025-05-30 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0009_alter_atleta_altura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='atleta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='atletas/fotos/'),
        ),
    ]
