# Generated by Django 5.2 on 2025-05-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0010_remove_atleta_foto_url_atleta_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
