# Generated by Django 5.2 on 2025-05-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0012_alter_atleta_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atleta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_atletas/'),
        ),
    ]
