# Generated by Django 5.2 on 2025-06-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0013_alter_atleta_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='modalidade',
            field=models.CharField(choices=[('kata', 'Kata'), ('kumite', 'Kumite'), ('ambos', 'Ambos')], default='ambos', max_length=10),
        ),
        migrations.AddField(
            model_name='atleta',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=10),
        ),
    ]
