# Generated by Django 5.2 on 2025-06-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0014_add_status_modalidade_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atleta',
            name='modalidade',
        ),
        migrations.RemoveField(
            model_name='atleta',
            name='status',
        ),
    ]
