# Generated by Django 5.2 on 2025-07-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0015_remove_atleta_modalidade_remove_atleta_status'),
        ('competicoes', '0013_chaveamentokumite_partidakumite_pontuacaokumite'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.CreateModel(
            name='CertificadoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('graduacao', 'Graduação/Faixa'), ('conquista', 'Conquista/Campeonato'), ('medico', 'Atestado Médico'), ('curso', 'Curso/Capacitação'), ('arbitragem', 'Arbitragem'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('entidade_emissora', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_emissao', models.DateField()),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('valido', 'Válido'), ('expirando', 'Expirando'), ('expirado', 'Expirado'), ('suspenso', 'Suspenso')], default='valido', max_length=20)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='atletas.atleta')),
            ],
            options={
                'verbose_name': 'Certificado do Atleta',
                'verbose_name_plural': 'Certificados dos Atletas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticaAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_lutas', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('ippon_aplicados', models.IntegerField(default=0)),
                ('waza_ari_aplicados', models.IntegerField(default=0)),
                ('yuko_aplicados', models.IntegerField(default=0)),
                ('medalhas_ouro', models.IntegerField(default=0)),
                ('medalhas_prata', models.IntegerField(default=0)),
                ('medalhas_bronze', models.IntegerField(default=0)),
                ('melhor_luta', models.CharField(blank=True, max_length=200, null=True)),
                ('melhor_pontuacao', models.FloatField(default=0.0)),
                ('anos_experiencia', models.IntegerField(default=0)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='atletas.atleta')),
            ],
            options={
                'verbose_name': 'Estatística do Atleta',
                'verbose_name_plural': 'Estatísticas dos Atletas',
            },
        ),
        migrations.CreateModel(
            name='HistoricoCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('1º', '1º Lugar'), ('2º', '2º Lugar'), ('3º', '3º Lugar'), ('eliminado', 'Eliminado'), ('desclassificado', 'Desclassificado'), ('nao_participou', 'Não Participou')], max_length=20)),
                ('pontuacao', models.FloatField(default=0.0)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_participacao', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_competicoes', to='atletas.atleta')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competicoes.categoria')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.competicao')),
            ],
            options={
                'verbose_name': 'Histórico de Competição',
                'verbose_name_plural': 'Históricos de Competições',
                'ordering': ['-data_participacao'],
                'unique_together': {('atleta', 'competicao', 'categoria')},
            },
        ),
    ]
