# Generated by Django 5.2 on 2025-01-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0016_atleta_cpf_atleta_rg_certificadoatleta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atleta',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='motivo_inativacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
