# Generated by Django 5.2 on 2025-07-22 01:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inscricoes_online', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtletaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nome_completo', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('primeiro_acesso', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ultimo_acesso', models.DateTimeField(blank=True, null=True)),
                ('inscricao_origem', models.ForeignKey(help_text='Inscrição que originou este usuário', on_delete=django.db.models.deletion.CASCADE, related_name='atleta_user', to='inscricoes_online.inscricaoonline')),
            ],
            options={
                'verbose_name': 'Usuário Atleta',
                'verbose_name_plural': 'Usuários Atletas',
                'db_table': 'portal_atleta_user',
            },
        ),
        migrations.CreateModel(
            name='LogAtividadeAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('visualizacao', 'Visualização'), ('download', 'Download'), ('alteracao', 'Alteração'), ('inscricao', 'Inscrição'), ('pagamento', 'Pagamento')], max_length=20)),
                ('descricao', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('dados_extras', models.JSONField(blank=True, null=True)),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='portal_atleta.atletauser')),
            ],
            options={
                'verbose_name': 'Log de Atividade',
                'verbose_name_plural': 'Logs de Atividades',
                'db_table': 'portal_atleta_log',
                'ordering': ['-data_acao'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inscricao', 'Inscrição'), ('pagamento', 'Pagamento'), ('competicao', 'Competição'), ('resultado', 'Resultado'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('data_leitura', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('expirar_em', models.DateTimeField(blank=True, null=True)),
                ('link_acao', models.URLField(blank=True, help_text='Link para ação relacionada')),
                ('dados_extras', models.JSONField(blank=True, help_text='Dados adicionais da notificação', null=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='portal_atleta.atletauser')),
            ],
            options={
                'verbose_name': 'Notificação de Atleta',
                'verbose_name_plural': 'Notificações de Atletas',
                'db_table': 'portal_atleta_notificacao',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receber_email_inscricao', models.BooleanField(default=True)),
                ('receber_email_pagamento', models.BooleanField(default=True)),
                ('receber_email_competicao', models.BooleanField(default=True)),
                ('receber_email_resultado', models.BooleanField(default=True)),
                ('perfil_publico', models.BooleanField(default=False)),
                ('mostrar_resultados', models.BooleanField(default=True)),
                ('mostrar_estatisticas', models.BooleanField(default=True)),
                ('tema_escuro', models.BooleanField(default=False)),
                ('idioma', models.CharField(default='pt-br', max_length=10)),
                ('configuracoes_extras', models.JSONField(blank=True, null=True)),
                ('atleta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to='portal_atleta.atletauser')),
            ],
            options={
                'verbose_name': 'Preferência de Atleta',
                'verbose_name_plural': 'Preferências de Atletas',
                'db_table': 'portal_atleta_preferencia',
            },
        ),
        migrations.CreateModel(
            name='SessaoAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_atividade', models.DateTimeField(auto_now=True)),
                ('ativa', models.BooleanField(default=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='portal_atleta.atletauser')),
            ],
            options={
                'verbose_name': 'Sessão de Atleta',
                'verbose_name_plural': 'Sessões de Atletas',
                'db_table': 'portal_atleta_sessao',
            },
        ),
    ]
