# Generated by Django 5.2 on 2025-05-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('modalidade', models.CharField(max_length=50)),
                ('data_inicio', models.DateTimeField()),
                ('horario', models.CharField()),
                ('local', models.CharField(max_length=150)),
                ('arbitros', models.TextField(blank=True, null=True)),
                ('regras_especificas', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ativa', 'Aiva'), ('Finalizada', 'Finalizada'), ('Em breve', 'Em breve')], max_length=20)),
            ],
        ),
    ]
