# Generated by Django 5.2 on 2025-05-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='competicao',
            name='status',
            field=models.CharField(default='Ativa', max_length=20),
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('MX', 'Misto')], max_length=2)),
                ('tipo', models.CharField(choices=[('GI', 'Gi'), ('NOGI', 'No-Gi'), ('ABS', 'Absolute')], max_length=10)),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='competicoes.competicao')),
            ],
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('idade', models.PositiveIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('faixa', models.CharField(choices=[('BRANCA', 'Branca'), ('AZUL', 'Azul'), ('ROXA', 'Roxa'), ('MARROM', 'Marrom'), ('PRETA', 'Preta')], max_length=10)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='atletas/')),
                ('academia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competicoes.academia')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atletas', to='competicoes.categoria')),
            ],
        ),
    ]
