# Generated by Django 5.2 on 2025-05-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0002_academia_alter_competicao_status_categoria_atleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='competicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academias', to='competicoes.competicao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competicao',
            name='inscricoes_abertas',
            field=models.BooleanField(default=False),
        ),
    ]
