# Generated by Django 5.2 on 2025-05-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0003_academia_competicao_competicao_inscricoes_abertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academia',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
