# Generated by Django 5.2 on 2025-05-28 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0004_alter_academia_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='horario',
            field=models.CharField(max_length=50),
        ),
    ]
