# Generated by Django 5.2 on 2025-05-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0005_alter_competicao_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competicao',
            name='inscricoes_abertas',
            field=models.BooleanField(default=True, help_text='Marque se as inscrições estão abertas', verbose_name='Inscrições Abertas?'),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='status',
            field=models.CharField(choices=[('Ativa', 'Ativa'), ('Cancelada', 'Cancelada'), ('Concluída', 'Concluída')], default='Ativa', max_length=20),
        ),
        migrations.DeleteModel(
            name='Atleta',
        ),
    ]
