# Generated by Django 5.2 on 2025-06-08 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0013_alter_atleta_foto'),
        ('competicoes', '0006_alter_competicao_inscricoes_abertas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartidaKumite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.PositiveIntegerField()),
                ('numero', models.PositiveIntegerField()),
                ('area', models.CharField(max_length=1)),
                ('pontos_aka', models.PositiveIntegerField(default=0)),
                ('pontos_ao', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Não Iniciada', 'Não Iniciada'), ('Em Andamento', 'Em Andamento'), ('Pausada', 'Pausada'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Não Iniciada', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_aka', to='atletas.atleta')),
                ('ao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_ao', to='atletas.atleta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_kumite', to='competicoes.categoria')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidas_vencidas', to='atletas.atleta')),
            ],
            options={
                'ordering': ['fase', 'numero'],
                'unique_together': {('categoria', 'fase', 'numero')},
            },
        ),
    ]
