# Generated by Django 5.2 on 2025-06-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0007_partidakumite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartidaKumite',
        ),
    ]
