# Generated by Django 5.2 on 2025-06-09 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0013_alter_atleta_foto'),
        ('competicoes', '0008_delete_partidakumite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoKata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField()),
                ('nota2', models.FloatField()),
                ('nota3', models.FloatField()),
                ('nota4', models.FloatField()),
                ('nota5', models.FloatField()),
                ('total', models.FloatField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_kata', to='atletas.atleta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.categoria')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.competicao')),
            ],
            options={
                'unique_together': {('atleta', 'categoria')},
            },
        ),
    ]
