# Generated by Django 5.2 on 2025-06-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0013_alter_atleta_foto'),
        ('competicoes', '0010_arbitro_alter_competicao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadokata',
            options={'ordering': ['-total', 'posicao']},
        ),
        migrations.AlterUniqueTogether(
            name='resultadokata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='resultadokata',
            name='fase',
            field=models.CharField(choices=[('eliminatorias', 'Eliminatórias'), ('semifinal', 'Semifinal'), ('final', 'Final')], default='eliminatorias', max_length=20),
        ),
        migrations.AddField(
            model_name='resultadokata',
            name='posicao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultadokata',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('classificado', 'Classificado'), ('eliminado', 'Eliminado')], default='ativo', max_length=20),
        ),
        migrations.AlterField(
            model_name='resultadokata',
            name='nota1',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resultadokata',
            name='nota2',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resultadokata',
            name='nota3',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resultadokata',
            name='nota4',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resultadokata',
            name='nota5',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resultadokata',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='resultadokata',
            unique_together={('atleta', 'categoria', 'fase')},
        ),
        migrations.CreateModel(
            name='ChaveamentoKata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase_atual', models.CharField(choices=[('eliminatorias', 'Eliminatórias'), ('semifinal', 'Semifinal'), ('final', 'Final')], default='eliminatorias', max_length=20)),
                ('finalizado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chaveamento_kata', to='competicoes.categoria')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.competicao')),
            ],
        ),
    ]
