# Generated by Django 5.2 on 2025-06-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competicoes', '0011_alter_resultadokata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadokata',
            name='salvo',
            field=models.BooleanField(default=False),
        ),
    ]
