# Generated by Django 5.2 on 2025-06-30 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atletas', '0015_remove_atleta_modalidade_remove_atleta_status'),
        ('competicoes', '0012_resultadokata_salvo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaveamentoKumite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_chaveamento', models.CharField(choices=[('eliminacao_simples', 'Eliminação Simples'), ('eliminacao_dupla', 'Eliminação Dupla'), ('grupo_eliminacao', 'Grupos + Eliminação')], default='eliminacao_simples', max_length=20)),
                ('fase_atual', models.CharField(default='oitavas', max_length=50)),
                ('finalizado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chaveamento_kumite', to='competicoes.categoria')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.competicao')),
            ],
        ),
        migrations.CreateModel(
            name='PartidaKumite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(max_length=50)),
                ('round_numero', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('resultado', models.CharField(blank=True, choices=[('vitoria_atleta1', 'Vitória Atleta 1'), ('vitoria_atleta2', 'Vitória Atleta 2'), ('empate', 'Empate'), ('wo_atleta1', 'WO Atleta 1'), ('wo_atleta2', 'WO Atleta 2'), ('desqualificacao_atleta1', 'Desqualificação Atleta 1'), ('desqualificacao_atleta2', 'Desqualificação Atleta 2')], max_length=30, null=True)),
                ('pontos_atleta1', models.IntegerField(default=0)),
                ('pontos_atleta2', models.IntegerField(default=0)),
                ('advertencias_atleta1', models.IntegerField(default=0)),
                ('advertencias_atleta2', models.IntegerField(default=0)),
                ('penalidades_atleta1', models.IntegerField(default=0)),
                ('penalidades_atleta2', models.IntegerField(default=0)),
                ('tempo_luta', models.DurationField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atleta1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_kumite_atleta1', to='atletas.atleta')),
                ('atleta2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidas_kumite_atleta2', to='atletas.atleta')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.categoria')),
                ('chaveamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='competicoes.chaveamentokumite')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competicoes.competicao')),
                ('vencedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vitorias_kumite', to='atletas.atleta')),
            ],
            options={
                'ordering': ['fase', 'round_numero'],
                'unique_together': {('chaveamento', 'fase', 'round_numero')},
            },
        ),
        migrations.CreateModel(
            name='PontuacaoKumite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ippon', 'Ippon (3 pontos)'), ('waza_ari', 'Waza-ari (2 pontos)'), ('yuko', 'Yuko (1 ponto)'), ('chukoku', 'Chukoku (Advertência)'), ('keikoku', 'Keikoku (Penalidade)'), ('hansoku_chui', 'Hansoku-chui (Penalidade Grave)'), ('hansoku', 'Hansoku (Desqualificação)')], max_length=20)),
                ('pontos', models.IntegerField(default=0)),
                ('tempo_acao', models.DurationField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atletas.atleta')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='competicoes.partidakumite')),
            ],
            options={
                'ordering': ['data_criacao'],
            },
        ),
    ]
